{
 "title": "The Smart Haus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Essentials", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select temperature from th_data;"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "Select humidity from th_data;" }
   ]
  },
  {
   "title": "Current Brightness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select brightness from mb_data;"
    }
   ]
  },
  {
   "title": "Motion Detected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "Select motion from mb_data;" }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HausAI",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Auto-refreshing Iframe</title>\n    <script>\n        // Function to refresh the iframe content every 5 seconds\n        function refreshIframe() {\n            const iframe = document.getElementById(\"myIframe\");\n            // Get the current iframe src\n            const currentSrc = iframe.src;\n            // Update the src by appending a query parameter to force reload\n            iframe.src = \"\";  // Empty the iframe to stop it temporarily\n            iframe.src = currentSrc + \"?timestamp=\" + new Date().getTime();  // Re-add the URL with a new timestamp to force refresh\n        }\n\n        setInterval(refreshIframe, 5000);  // Refresh every 5 seconds\n    </script>\n</head>\n<body>\n    <iframe id=\"myIframe\" src=\"http://localhost:9092/data/ml_brightness/ml_brightness.txt\" width=\"1300\" height=\"350\">\n        Loading content...\n    </iframe>\n</body>\n</html>"
   }
  },
  { "title": "Environmental Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "Select temperature, created_at from th_data;\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "Select humidity, created_at from th_data;\n"
    }
   ]
  },
  {
   "title": "Brightness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "rawSql": "Select brightness, created_at from mb_data;\n"
    }
   ]
  },
  {
   "title": "Person Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "Select motion, created_at from mb_data;\n"
    }
   ]
  },
  { "title": "Intrusion Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "DoorCam",
   "type": "text",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 70 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Auto-refreshing Image</title>\n    <script>\n        // Function to reload the image every 5 seconds (or adjust as needed)\n        function refreshImage() {\n            const image = document.getElementById(\"auto-refresh-image\");\n            image.src = \"http://localhost:9092/data/images/image.jpeg?timestamp=\" + new Date().getTime();\n        }\n        setInterval(refreshImage, 5000); // Refresh every 5 seconds\n    </script>\n</head>\n<body>\n    <img id=\"auto-refresh-image\" src=\"http://localhost:9092/data/images/image.jpeg\" alt=\"Description\" width=\"600\" height=\"400\">\n</body>\n</html>"
   }
  },
  {
   "title": "Disarm Alarm",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 70 },
   "options": {
    "content": "<div id=\"controlButton\">\n  <button id=\"toggleButton\" onclick=\"turnOff()\" style=\"padding: 10px 20px; font-size: 16px; background-color: red; color: white; border: none; cursor: pointer;\">\n    Disarm Alarm\n  </button>\n</div>\n\n<script>\n  function turnOff() {\n    // Set ESP32 IP and fixed \"off\" state\n    const esp32IP = \"http://192.168.115.50/setStatus\";  // Replace with your ESP32 IP\n    const state = \"off\";\n\n    // Send the HTTP POST request to ESP32 with the state \"off\"\n    fetch(`${esp32IP}?state=${state}`, {\n      method: \"POST\",\n      headers: {\n        \"Content-Type\": \"application/x-www-form-urlencoded\"\n      }\n    })\n    .then(response => {\n      if (response.ok) {\n        console.log(\"ESP32 state set to: off\");\n      } else {\n        console.error(\"Error sending request to ESP32\");\n      }\n    })\n    .catch(error => {\n      console.error(\"Network error:\", error);\n    });\n  }\n</script>"
   }
  },
  {
   "title": "Intruder Detected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 70 },
   "targets": [
    {
     "rawSql": "Select intrusion, created_at from door_data;\n"
    }
   ]
  },
  {
   "title": "HausAI",
   "type": "text",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 75 },
   "options": {
    "content": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Auto-refreshing Iframe</title>\n    <script>\n        // Function to refresh the iframe content every 5 seconds\n        function refreshIframe() {\n            const iframe = document.getElementById(\"myIframe\");\n            // Get the current iframe src\n            const currentSrc = iframe.src;\n            // Update the src by appending a query parameter to force reload\n            iframe.src = \"\";  // Empty the iframe to stop it temporarily\n            iframe.src = currentSrc + \"?timestamp=\" + new Date().getTime();  // Re-add the URL with a new timestamp to force refresh\n        }\n\n        setInterval(refreshIframe, 5000);  // Refresh every 5 seconds\n    </script>\n</head>\n<body>\n    <iframe id=\"myIframe\" src=\"http://localhost:9092/data/ml_image/ml_image.txt\" width=\"700\" height=\"200\">\n        Loading content...\n    </iframe>\n</body>\n</html>"
   }
  }
 ]
}