version: '3.8'
services:
  tsh-server:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DB_URL=postgresql://admin:admin@postgres:5432/tsh-backend

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tsh-backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: